apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: db
    spec:
      containers:
        - args:
            - mysqld
            - --default-authentication-plugin=mysql_native_password
          env:
            - name: MYSQL_PASSWORD
              value: "12345678"
            - name: MYSQL_ROOT_PASSWORD
              value: "12345678"
            - name: MYSQL_USER
              value: k8s
          image: mysql:5.7
          args:
            - "--ignore-db-dir=lost+found" # https://github.com/docker-library/mysql/issues/69
          name: db
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db-data
      restartPolicy: Always
      volumes:
        - name: db-data # Link volume with a persistentVolumeClaim
          persistentVolumeClaim:
            claimName: db-data
